# Generated by Django 4.1 on 2022-08-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='date')),
                ('time', models.CharField(max_length=5, verbose_name='time')),
                ('gmail', models.CharField(max_length=50, verbose_name='gmail')),
                ('question', models.TextField(verbose_name='question')),
            ],
        ),
    ]
