# Generated by Django 4.1 on 2022-08-16 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_db_landing_landing_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_landing',
            name='active',
            field=models.CharField(default=django.utils.timezone.now, max_length=6, verbose_name='active'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landing',
            name='active',
            field=models.CharField(default=123, max_length=6, verbose_name='active'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='active',
            field=models.CharField(default=111, max_length=6, verbose_name='active'),
            preserve_default=False,
        ),
    ]
