# Generated by Django 4.1 on 2022-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_db_landing_active_landing_active_shop_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_landing',
            name='active',
            field=models.CharField(max_length=20, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='active',
            field=models.CharField(max_length=20, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='active',
            field=models.CharField(max_length=20, verbose_name='active'),
        ),
    ]
