# Generated by Django 4.1 on 2022-08-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_db_landing_active_alter_landing_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_landing',
            name='active',
            field=models.CharField(max_length=22, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='active',
            field=models.CharField(max_length=22, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='active',
            field=models.CharField(max_length=22, verbose_name='active'),
        ),
    ]
